### ISSUE TITLE
Code does not work

### ISSUE THREAD

**Issue by gaoyike** [gravityonmars/nodejs-starter#22]
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
  njs Application started on port 3000 +716ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: failed to connect to [localhost:27017]
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
make: **\* [run] Error 1

**Comment by cristiandouce** [comment]
Would you be more specific about your environment like OS, version, node and npm version... 
Do you have mongo running? I see there that you were unable to connect to mongodb for instance.

**Comment by bhanuc** [comment]
It says in the error log itself

```
Error: failed to connect to [localhost:27017] 
```

Your mongodb instance is not running. You can try to run the client using mongo command or use the mongod command to start mongodb
